version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app  # Your app's destination folder on the EC2 instance
  - source: /sign to text data/
    destination: /home/ec2-user/app/sign_to_text_data
  - source: /text to sign data/
    destination: /home/ec2-user/app/text_to_sign_data
  - source: /models/
    destination: /home/ec2-user/app/models

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/setup_application.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user

